version: 2
updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Asia/Tokyo"
    directory: "/"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "_"
    rebase-strategy: "auto"
    versioning-strategy: increase-if-necessary
  - package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    directory: "/"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    commit-message:
      prefix: "check ci status"
      include: "scope"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "_"
    rebase-strategy: "auto"
