changelog:
  categories:
    - title: 新機能
      labels:
        - enhance-2 新機能
    - title: 後方互換性の破壊
      labels:
        - enhance-1 破壊的変更
    - title: バグ修正
      labels:
        - bug-1 重大バグ
        - bug-2 バグ
    - title: メンテナンス
      labels:
        - bug-3 改善
        - enhance-3 ドキュメント
        - dependencies
        - refactor
  exclude:
    labels:
      - blocked by
      - close-1 お見送り
      - close-2 重複
      - close-3 再現不能
      - topic-1 参考情報
