name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '新機能'
    labels:
      - 'enhance-2 新機能'
      - 'enhance-3 破壊的変更'
  - title: '後方互換性の破壊'
    labels:
      - 'enhance-3 破壊的変更'
  - title: 'バグ修正'
    labels:
      - 'bug-1 重大バグ'
      - 'bug-2 バグ'
  - title: 'メンテナンス'
    labels:
      - 'bug-3 改善'
      - 'refactor'
      - 'dependencies'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'close-1 お見送り'
  - 'close-2 重複'
  - 'close-3 再現不能'
template: |
  ## 概要
  -
  ## 詳細
  $CHANGES
  ## 備考
  -
