name: build-check

on:
  schedule:
    - cron: 0 22 1 * *

jobs:
  file-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: files check
        run: |
          ls ${{ env.src-path }} | grep index.html
          ls ${{ env.src-path }}/materials/ | grep cymbals.mp3
          ls ${{ env.src-path }}/materials/ | grep drumroll.mp3
          ls ${{ env.src-path }}/materials/ | grep logo.ico
        env:
          src-path: ${GITHUB_WORKSPACE}/src

  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: use cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.npm
          key: ${cache-version}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${cache-version}-node-
        env:
          cache-version: v1
      - name: npm ci and build
        run: |
          npm ci
          npm run build
