name: build-check

on:
  schedule:
    - cron: 0 22 1 * *

jobs:
  file-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Files check
        run: |
          ls ${{ env.src-path }} | grep index.html
          ls ${{ env.src-path }}/materials/ | grep cymbals.mp3
          ls ${{ env.src-path }}/materials/ | grep drumroll.mp3
          ls ${{ env.src-path }}/materials/ | grep logo.ico
        env:
          src-path: ${GITHUB_WORKSPACE}/docs

  build-ts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache
        uses: actions/cache@v2.1.2
        with:
          path: ~/.npm
          key: ${cache-version}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${cache-version}-node-
        env:
          cache-version: v1
      - name: npm ci and build
        run: |
          npm ci
          npm run build
