name: CleanDocs

on:
  pull_request:
    branches:
      - deploy_fix
  push:
    branches:
      - deploy_fix

jobs:
  RemoveDocsFiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: deploy_fix
      - name: Check Files
        shell:
          bash
          # gitの仕様上、ディレクトリがあれば配下にファイルが存在する
        run: |
          [ -d ${GITHUB_WORKSPACE}/docs/ ] && echo exists docs
        continue-on-error: true
      - name: Remove & Commit
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v5.1.0
        with:
          remove: docs/ -r
          author_name: ${GITHUB_EVENT_NAME}
          author_email: ${{ secrets.EMAIL_ADDRESS }}
          branch: deploy_fix
          message: "clean docs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: deploy_fix
