name: Monitoring

on:
  pull_request:
    branches:
      - main

jobs:
  RemoveDocsFiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: "main"
      - name: Files Check
        run: |
          rm -r ${{ env.src-path }}
        env:
          src-path: ${GITHUB_WORKSPACE}/docs
      - name: Remove & Commit
        uses: EndBug/add-and-commit@v5.1.0
        with:
          remove: ${GITHUB_WORKSPACE}/docs/*
          author_name: ${GITHUB_EVENT_NAME}
          author_email: ${{ secrets.EMAIL_ADDRESS }}
          branch: main
          message: "clean docs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
