name: Deploy

on:
  pull_request:
    branches:
      - main
      - release
    paths:
      - src/**
  push:
    branches:
      - release
    paths:
      - src/**

jobs:
  BuildTS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.ref }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache
        uses: actions/cache@v2.1.2
        with:
          path: ~/.npm
          key: ${cache-version}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${cache-version}-node-
        env:
          cache-version: v1
      - name: npm ci and build
        run: |
          npm ci
          npm run build
      - name: upload materials
        if: github.ref == 'refs/heads/release'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: js
          path: src/js

  MoveHTMLAndMaterials:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: release
      - name: Upload HTML
        uses: actions/upload-artifact@v2
        with:
          name: html
          path: src/index.html
      - name: Upload Materials
        uses: actions/upload-artifact@v2
        with:
          name: materials
          path: src/materials

  GitPush:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    needs:
      - BuildTs
      - MoveHTMLAndMaterials
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: release
      - name: MkDir
        run: |
          mkdir -p docs/materials
          mkdir -p docs/js
      - name: Download HTML
        uses: actions/download-artifact@v2
        with:
          name: html
          path: docs
      - name: Download Materials
        uses: actions/download-artifact@v2
        with:
          name: materials
          path: docs/materials
      - name: Download JavaScript
        uses: actions/download-artifact@v2
        with:
          name: js
          path: docs/js
      - name: Add & Commit
        uses: EndBug/add-and-commit@v5.1.0
        with:
          add: $docs/ -r
          author_name: ${{ github.event_name }}
          author_email: ${{ secrets.EMAIL_ADDRESS }}
          branch: release
          message: "deploy"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
