name: Deploy pages

on:
  workflow_dispatch:
    inputs:
      confirm:
        required: true
        description: "本当に実行しますか？実行する場合「run」と書いてください。"
      environment:
        required: true
        description: "反映対象の環境"
        type: environment
  pull_request:
    types: [review_requested, reopened, ready_for_review]
    branches:
      - main

jobs:
  Prior-Confirmation:
    name: Dependency Review
    uses: ./.github/workflows/dependency-review.yml
  Deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Confirm Check
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirm != 'run'
        run: echo "Invalid input" && exit 1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          check-latest: true
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Clean Up
        run: rm -r src/ts
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: github-pages
          build_dir: src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
