name: Deploy

on:
  pull_request:
    branches:
      - main
      - release
    paths:
      - src/*
  push:
    branches:
      - deploy_fix
    #   - release
    # paths:
    #   - src/*

jobs:
  BuildTS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache
        uses: actions/cache@v2.1.2
        with:
          path: ~/.npm
          key: ${cache-version}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${cache-version}-node-
        env:
          cache-version: v1
      - name: npm ci and build
        run: |
          npm ci
          npm run build
      - name: upload materials
        if: github.base_ref == 'release'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: js
          path: src/js

  MoveHTMLAndMaterials:
    runs-on: ubuntu-latest
    if: github.base_ref == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Upload HTML
        uses: actions/upload-artifact@v2
        with:
          name: html
          path: src/index.html
      - name: Upload Materials
        uses: actions/upload-artifact@v2
        with:
          name: materials
          path: src/materials

  GitPush:
    runs-on: ubuntu-latest
    if: github.base_ref == 'release'
    needs:
      - BuildTs
      - MoveHTMLAndMaterials
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.base_ref }}
      - name: MkDir
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/docs/materials
          mkdir -p ${GITHUB_WORKSPACE}/docs/js
      - name: Download HTML
        uses: actions/download-artifact@v2
        with:
          name: html
          path: docs
      - name: Download Materials
        uses: actions/download-artifact@v2
        with:
          name: materials
          path: docs/materials
      - name: Download JavaScript
        uses: actions/download-artifact@v2
        with:
          name: js
          path: docs/js
      - name: Add & Commit
        uses: EndBug/add-and-commit@v5.1.0
        with:
          add: ${GITHUB_WORKSPACE}/docs/*
          author_name: ${GITHUB_EVENT_NAME}
          author_email: ${{ secrets.EMAIL_ADDRESS }}
          branch: main
          message: "deploy"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.base_ref }}
