name: deploy

on:
  push:
    branches-ignore:
      - "!master"
    tags:
      - v*.*.*

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: file delete and copy
        run: |
          rm docs/index.html
          rm docs/materials/*
          cp src/index.html docs/
          cp src/materials/* docs/materials/
  ts-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build
