name: deploy

on:
  push:
    branches:
      - master
    paths:
      - docs/index.html
      - docs/ts/*
      - docs/materials/*

jobs:
  build-ts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache
        uses: actions/cache@v2.1.2
        with:
          path: ~/.npm
          key: ${cache-version}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${cache-version}-node-
        env:
          cache-version: v1
      - name: npm ci and build
        run: |
          npm ci
          npm run build

  git-push:
    runs-on: ubuntu-latest
    needs: ["build-ts"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: mkdir
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/docs/js
      - name: Commit
        run: |
          git config --local user.name ${git-name}
          git config --local user.email ${git-email}
          git pull
          git add docs/*
          git commit --allow-empty -m "deploy"
        env:
          git-name: ${GITHUB_EVENT_NAME}
          git-email: ${{ secrets.EMAIL_ADDRESS }}
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
