name: deploy

on:
  push:
    branches:
      - master
      - docs保持
    tags:
      - v*.*.*

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: file delete and copy
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/docs/materials
          cp -f  ${GITHUB_WORKSPACE}/src/index.html docs/
          cp -f  ${GITHUB_WORKSPACE}/src/materials/* docs/materials/

  ts-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build
      - name: use cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.npm
          key: ${{ env.cache-version }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ env.cache-version }}-node-
      - name: npm ci and build
        run: |
          npm ci
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: ["copy", "ts-build"]
    steps:
      - name: commit files
        run: |
          git config --local user.email "bingo_deployer@github.actions"
          git config --local user.name "bingo deployer"
          git commit -m "deploy" -a
      - name: push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
