name: Deploy pages

on:
  workflow_dispatch:
    inputs:
      confirm:
        required: true
        description: "本当に実行しますか？実行する場合「run」と書いてください。"
      environment:
        required: true
        description: "反映対象の環境"
        type: environment
  push:
    branches:
      - main

# デフォルトシェルでパイプエラーを有効化
defaults:
  run:
    shell: bash

# ワークフローが複数起動したら自動キャンセル
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    timeout-minutes: 5
    permissions: {}
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - name: Confirm Check
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirm != 'run'
        run: echo "Invalid input" && exit 1
      - uses: actions/checkout@v5
      - name: Run actionlint in workflow Directory
        run: |
          set -x
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:1.7.4
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.0
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Clean Up
        run: rm -r src/ts
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "src/"
  Deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs:
      - Build
    permissions:
      pages: write
      id-token: write
    timeout-minutes: 5
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - id: deployment
        uses: actions/deploy-pages@v4
