name: deploy

on:
  push:
    branches:
      - fix_deploy
      # - maste
    # paths:
    # - src/*

jobs:
  html-and-materials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: upload html
        uses: actions/upload-artifact@v1.0.0
        with:
          name: html
          path: src/index.html
      - name: upload materials
        uses: actions/upload-artifact@v1.0.0
        with:
          name: materials
          path: src/materials

  build-ts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache
        uses: actions/cache@v2.1.2
        with:
          path: ~/.npm
          key: ${cache-version}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${cache-version}-node-
        env:
          cache-version: v1
      - name: npm ci and build
        run: |
          npm ci
          npm run build
      - name: upload materials
        uses: actions/upload-artifact@v1.0.0
        with:
          name: js
          path: src/js

  make-docs:
    runs-on: ubuntu-latest
    needs: ["html-and-materials", "build-ts"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: mkdir
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/docs/materials
          mkdir -p ${GITHUB_WORKSPACE}/docs/js
      - name: download html
        uses: actions/download-artifact@v1.0.0
        with:
          name: html
          path: docs
      - name: download materials
        uses: actions/download-artifact@v1.0.0
        with:
          name: materials
          path: docs/materials
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: js
          path: docs/js
      - name: commit files
        run: |
          git config --local user.name ${git-name}
          git config --local user.email ${git-email}
          git pull
          git add docs/*
          git commit -m "deploy"
        env:
          git-name: ${GITHUB_EVENT_NAME}
          git-email: ${{ secrets.EMAIL_ADDRESS }}
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
