name: deploy

on:
  push:
    branches:
      - actions修正
    tags:
      - v*.*.*

jobs:
  file-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: if exists index.html
        run: |
          ls ${GITHUB_WORKSPACE}/src/ | grep index.html
      - name: if exists materials
        run: |
          ls ${GITHUB_WORKSPACE}/src/materials/ | grep cynmbals.mp3
          ls ${GITHUB_WORKSPACE}/src/materials/ | grep drumroll.mp3
          ls ${GITHUB_WORKSPACE}/src/materials/ | grep logo.ico

  file-copy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: file delete and copy
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/docs/materials
          cp -f  ${GITHUB_WORKSPACE}/src/index.html docs/
          cp -f  ${GITHUB_WORKSPACE}/src/materials/* docs/materials/

  ts-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build
      - name: use cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.npm
          key: ${{ env.cache-version }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ env.cache-version }}-node-
      - name: npm ci and build
        run: |
          npm ci
          npm run build
