name: Deploy pages

on:
  workflow_dispatch:
    inputs:
      confirm:
        required: true
        description: "本当に実行しますか？実行する場合「run」と書いてください。"
      environment:
        required: true
        description: "反映対象の環境"
        type: environment
  push:
    branches:
      - main
      - bugfix
      - feature

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Confirm Check
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirm != 'run'
        run: echo "Invalid input" && exit 1
      - uses: actions/checkout@v4
      - uses: build-check.yml
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean Up
        run: rm -r src/ts
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "src/"
  Deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs:
      - Build
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
