name: Deploy pages

on:
  pull_request:
    types: [assigned, review_requested, reopened, ready_for_review]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: clean up
        run: rm -r src/ts
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: release
          build_dir: src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
