name: deploy

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: file delete and copy
        run: |
          mkdir -p docs/materials
          cp -f src/index.html docs/
          cp -f src/materials/* docs/materials/
  ts-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build
