name: Monitoring

on:
  schedule:
    - cron: 0 22 * * 5

jobs:
  FileCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: "release"
      - name: Files check
        run: |
          ls ${{ env.src-path }} | grep index.html
          ls ${{ env.src-path }}/materials/ | grep cymbals.mp3
          ls ${{ env.src-path }}/materials/ | grep drumroll.mp3
          ls ${{ env.src-path }}/materials/ | grep logo.ico
        env:
          src-path: ${GITHUB_WORKSPACE}/docs
