name: ready for deploy

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
    branches:
      - master

jobs:
  ts-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@master
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci and build
        run: |
          npm ci
          npm run build
  file-check:
    runs-on: ubuntu-latest
    steps:
      - name: if exists index.html
        run: |
          ls | grep src/index.html
      - name: if exists materials
        run: |
          ls | grep src/materials/cynmbals.mp3
          ls | grep src/materials/drumroll.mp3
          ls | grep src/materials/logo.ico
