name: PrepareReleaseNote

on:
  pull_request:
    types:
      - synchronize
  push:
    branches:
      - release

jobs:
  create-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.19.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
