name: prepare-release-note

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  release-note-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}のリリース
          body: |
            ## 概要
            -
            ## 詳細
            -
            ## 備考
            -
          draft: true
          prerelease: true
