name: Synthetic Monitoring

on:
  schedule:
    - cron: 0 22 * * 5

# デフォルトシェルでパイプエラーを有効化
defaults:
  run:
    shell: bash

# ワークフローが複数起動したら自動キャンセル
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  monitoring:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: curl
        env:
          URL: https://rohta.github.io/bingo/
        run: curl "${URL}"
# 失敗時、即時対応しないため通知は不要。Actionsを見て都度対応。
